Partida = {
    "0101"  :  "Caballos, asnos, mulos y burdéganos, vivos",
    "0102"  :  "Animales vivos de la especie bovina",
    "0106"  :  "Los demás animales vivos",
    "0201"  :  "Carne de animales de la especie bovina, fresca o r...",
    "0202"  :  "Carne de animales de la especie bovina, congelada",
    "0203"  :  "Carne de animales de la especie porcina, fresca, r...",
    "0204"  :  "Carne de animales de las especies ovina o caprina,...",
    "0206"  :  "Despojos comestibles de animales de las especies b...",
    "0207"  :  "Carne y despojos comestibles, de aves de la partid...",
    "0209"  :  "Tocino sin partes magras y grasa de cerdo o de ave...",
    "0210"  :  "Carne y despojos comestibles, salados o en salmuer...",
    "0301"  :  "Peces vivos",
    "0302"  :  "Pescado fresco o refrigerado, excepto los filetes ...",
    "0303"  :  "Pescado congelado, excepto los filetes y demás car...",
    "0304"  :  "Filetes y demás carne de pescado (incluso picada),...",
    "0305"  :  "Pescado seco, salado o en salmuera; pescado ahumad...",
    "0306"  :  "Crustáceos, incluso pelados, vivos, frescos, refri...",
    "0307"  :  "Moluscos, incluso separados de sus valvas, vivos, ...",
    "0308"  :  "Invertebrados acuáticos, excepto los crustáceos y ...",
    "0401"  :  "Leche y nata (crema), sin concentrar, sin adición ...",
    "0402"  :  "Leche y nata (crema), concentradas o con adición d...",
    "0403"  :  "Suero de mantequilla, leche y nata (crema) cuajada...",
    "0404"  :  "Lactosuero, incluso concentrado o con adición de a...",
    "0405"  :  "Mantequilla y demás materias grasas de la leche; p...",
    "0406"  :  "Quesos y requesón",
    "0407"  :  "Huevos de ave con cáscara (cascarón), frescos, con...",
    "0409"  :  "Miel natural",
    "0410"  :  "Productos comestibles de origen animal no expresad...",
    "0504"  :  "Tripas, vejigas y estómagos de animales, excepto l...",
    "0506"  :  "Huesos y núcleos córneos, en bruto, desgrasados, s...",
    "0507"  :  "Marfil, concha (caparazón) de tortuga, ballenas de...",
    "0508"  :  "Coral y materias similares, en bruto o simplemente...",
    "0510"  :  "Ámbar gris, castóreo, algalia y almizcle; cantárid...",
    "0511"  :  "Productos de origen animal no expresados ni compre...",
    "0602"  :  "Las demás plantas vivas (incluidas sus raíces), es...",
    "0603"  :  "Flores y capullos, cortados para ramos o adornos, ...",
    "0604"  :  "Follaje, hojas, ramas y demás partes de plantas, s...",
    "0701"  :  "Papas (patatas) frescas o refrigeradas",
    "0702"  :  "Tomates frescos o refrigerados",
    "0703"  :  "Cebollas, chalotes, ajos, puerros y demás hortaliz...",
    "0704"  :  "Coles, incluidos los repollos, coliflores, coles r...",
    "0705"  :  "Lechugas (Lactuca sativa) y achicorias, comprendid...",
    "0706"  :  "Zanahorias, nabos, remolachas para ensalada, salsi...",
    "0707"  :  "Pepinos y pepinillos, frescos o refrigerados",
    "0708"  :  "Hortalizas de vaina, aunque estén desvainadas, fre...",
    "0709"  :  "Las demás hortalizas, frescas o refrigeradas",
    "0710"  :  "Hortalizas, aunque estén cocidas en agua o vapor, ...",
    "0711"  :  "Hortalizas conservadas provisionalmente (por ejemp...",
    "0712"  :  "Hortalizas secas, incluidas las cortadas en trozos...",
    "0713"  :  "Hortalizas de vaina secas desvainadas, aunque esté...",
    "0714"  :  "Raíces de yuca (mandioca), arrurruz o salep, aguat...",
    "0801"  :  "Cocos, nueces del Brasil y nueces de marañón (mere...",
    "0802"  :  "Los demás frutos de cáscara frescos o secos, inclu...",
    "0803"  :  "Bananas, incluidos los plátanos para cocinar (plan...",
    "0804"  :  "Dátiles, higos, piñas (ananás), aguacates (paltas)...",
    "0805"  :  "Agrios (cítricos) frescos o secos",
    "0806"  :  "Uvas, frescas o secas, incluidas las pasas",
    "0807"  :  "Melones, sandías y papayas, frescos",
    "0808"  :  "Manzanas, peras y membrillos, frescos",
    "0809"  :  "Chabacanos (damascos, albaricoques), cerezas, dura...",
    "0810"  :  "Las demás frutas u otros frutos, frescos",
    "0811"  :  "Frutas y otros frutos, sin cocer o cocidos en agua...",
    "0812"  :  "Frutas y otros frutos, conservados provisionalment...",
    "0813"  :  "Frutas y otros frutos, secos, excepto los de las p...",
    "0814"  :  "Cortezas de agrios (cítricos), melones o sandías, ...",
    "0901"  :  "Café, incluso tostado o descafeinado; cáscara y ca...",
    "0902"  :  "Té, incluso aromatizado",
    "0904"  :  "Pimienta del género Piper; frutos de los géneros C...",
    "0905"  :  "Vainilla",
    "0906"  :  "Canela y flores de canelero",
    "0907"  :  "Clavo (frutos, clavillos y pedúnculos)",
    "0908"  :  "Nuez moscada, macis, amomos y cardamomos",
    "0909"  :  "Semillas de anís, badiana, hinojo, cilantro, comin...",
    "0910"  :  "Jengibre, azafrán, cúrcuma, tomillo, hojas de laur...",
    "1001"  :  "Trigo y morcajo (tranquillón)",
    "1005"  :  "Maíz",
    "1006"  :  "Arroz",
    "1008"  :  "Alforfón, mijo y alpiste; los demás cereales",
    "1101"  :  "Harina de trigo o de morcajo (tranquillón)",
    "1102"  :  "Harina de cereales, excepto de trigo o de morcajo ...",
    "1103"  :  "Grañones, sémola y 'pellets', de cereales",
    "1104"  :  "Granos de cereales trabajados de otro modo (por ej...",
    "1105"  :  "Harina, sémola, polvo, copos, gránulos y 'pellets'...",
    "1106"  :  "Harina, sémola y polvo de las hortalizas de la par...",
    "1107"  :  "Malta (de cebada u otros cereales), incluso tostad...",
    "1108"  :  "Almidón y fécula; inulina",
    "1201"  :  "Habas (frijoles, porotos, fréjoles) de soja (soya)...",
    "1202"  :  "Cacahuates (cacahuetes, maníes) sin tostar ni coce...",
    "1206"  :  "Semilla de girasol, incluso quebrantada",
    "1207"  :  "Las demás semillas y frutos oleaginosos, incluso q...",
    "1208"  :  "Harina de semillas o de frutos oleaginosos, except...",
    "1209"  :  "Semillas, frutos y esporas, para siembra",
    "1211"  :  "Plantas, partes de plantas, semillas y frutos de l...",
    "1212"  :  "Algarrobas, algas, remolacha azucarera y caña de a...",
    "1213"  :  "Paja y cascabillo de cereales, en bruto, incluso p...",
    "1214"  :  "Nabos forrajeros, remolachas forrajeras, raíces fo...",
    "1301"  :  "Goma laca; gomas, resinas, gomorresinas y oleorres...",
    "1302"  :  "Jugos y extractos vegetales; materias pécticas, pe...",
    "1401"  :  "Materias vegetales de las especies utilizadas prin...",
    "1404"  :  "Productos vegetales no expresados ni comprendidos ...",
    "1501"  :  "Grasa de cerdo (incluida la manteca de cerdo) y gr...",
    "1502"  :  "Grasa de animales de las especies bovina, ovina o ...",
    "1504"  :  "Grasas y aceites, y sus fracciones, de pescado o d...",
    "1505"  :  "Grasa de lana y sustancias grasas derivadas, inclu...",
    "1507"  :  "Aceite de soja (soya) y sus fracciones, incluso re...",
    "1509"  :  "Aceite de oliva y sus fracciones, incluso refinado...",
    "1510"  :  "Los demás aceites y sus fracciones obtenidos exclu...",
    "1511"  :  "Aceite de palma y sus fracciones, incluso refinado...",
    "1512"  :  "Aceites de girasol, cártamo o algodón, y sus fracc...",
    "1513"  :  "Aceites de coco (de copra), de almendra de palma o...",
    "1514"  :  "Aceites de nabo (de nabina), colza o mostaza, y su...",
    "1515"  :  "Las demás grasas y aceites vegetales fijos (inclui...",
    "1516"  :  "Grasas y aceites, animales o vegetales, y sus frac...",
    "1517"  :  "Margarina; mezclas o preparaciones alimenticias de...",
    "1518"  :  "Grasas y aceites, animales o vegetales, y sus frac...",
    "1520"  :  "Glicerol en bruto; aguas y lejías glicerinosas",
    "1521"  :  "Ceras vegetales (excepto los triglicéridos), cera ...",
    "1522"  :  "Degrás; residuos procedentes del tratamiento de gr...",
    "1601"  :  "Embutidos y productos similares de carne, despojos...",
    "1602"  :  "Las demás preparaciones y conservas de carne, desp...",
    "1604"  :  "Preparaciones y conservas de pescado; caviar y sus...",
    "1605"  :  "Crustáceos, moluscos y demás invertebrados acuátic...",
    "1701"  :  "Azúcar de caña o de remolacha y sacarosa químicame...",
    "1702"  :  "Los demás azúcares, incluidas la lactosa, maltosa,...",
    "1703"  :  "Melaza procedente de la extracción o del refinado ...",
    "1704"  :  "Artículos de confitería sin cacao (incluido el cho...",
    "1801"  :  "Cacao en grano, entero o partido, crudo o tostado",
    "1802"  :  "Cáscara, películas y demás residuos de cacao",
    "1803"  :  "Pasta de cacao, incluso desgrasada",
    "1804"  :  "Manteca, grasa y aceite de cacao",
    "1805"  :  "Cacao en polvo sin adición de azúcar ni otro edulc...",
    "1806"  :  "Chocolate y demás preparaciones alimenticias que c...",
    "1901"  :  "Extracto de malta; preparaciones alimenticias de h...",
    "1902"  :  "Pastas alimenticias, incluso cocidas o rellenas (d...",
    "1903"  :  "Tapioca y sus sucedáneos preparados con fécula, en...",
    "1904"  :  "Productos a base de cereales obtenidos por inflado...",
    "1905"  :  "Productos de panadería, pastelería o galletería, i...",
    "2001"  :  "Hortalizas, frutas u otros frutos y demás partes c...",
    "2002"  :  "Tomates preparados o conservados (excepto en vinag...",
    "2003"  :  "Hongos y trufas, preparados o conservados (excepto...",
    "2004"  :  "Las demás hortalizas preparadas o conservadas (exc...",
    "2005"  :  "Las demás hortalizas preparadas o conservadas (exc...",
    "2006"  :  "Hortalizas, frutas u otros frutos o sus cortezas y...",
    "2007"  :  "Confituras, jaleas y mermeladas, purés y pastas de...",
    "2008"  :  "Frutas u otros frutos y demás partes comestibles d...",
    "2009"  :  "Jugos de frutas u otros frutos (incluido el mosto ...",
    "2101"  :  "Extractos, esencias y concentrados de café, té o y...",
    "2102"  :  "Levaduras (vivas o muertas); los demás microorgani...",
    "2103"  :  "Preparaciones para salsas y salsas preparadas; con...",
    "2104"  :  "Preparaciones para sopas, potajes o caldos; sopas,...",
    "2105"  :  "Helados, incluso con cacao",
    "2106"  :  "Preparaciones alimenticias no expresadas ni compre...",
    "2201"  :  "Agua, incluidas el agua mineral natural o artifici...",
    "2202"  :  "Agua, incluidas el agua mineral y la gaseada, con ...",
    "2203"  :  "Cerveza de malta",
    "2204"  :  "Vino de uvas frescas, incluso encabezado; mosto de...",
    "2205"  :  "Vermut y demás vinos de uvas frescas preparados co...",
    "2206"  :  "Las demás bebidas fermentadas (por ejemplo: sidra,...",
    "2207"  :  "Alcohol etílico sin desnaturalizar con grado alcoh...",
    "2208"  :  "Alcohol etílico sin desnaturalizar con grado alcoh...",
    "2209"  :  "Vinagre y sucedáneos del vinagre obtenidos a parti...",
    "2301"  :  "Harina, polvo y 'pellets', de carne, despojos, pes...",
    "2302"  :  "Salvados, moyuelos y demás residuos del cernido, d...",
    "2303"  :  "Residuos de la industria del almidón y residuos si...",
    "2306"  :  "Tortas y demás residuos sólidos de la extracción d...",
    "2308"  :  "Materias vegetales y desperdicios vegetales, resid...",
    "2309"  :  "Preparaciones de los tipos utilizados para la alim...",
    "2401"  :  "Tabaco en rama o sin elaborar; desperdicios de tab...",
    "2402"  :  "Cigarros (puros) (incluso despuntados), cigarritos...",
    "2403"  :  "Los demás tabacos y sucedáneos del tabaco, elabora...",
    "2404"  :  "Productos que contengan tabaco, tabaco reconstitui...",
    "2501"  :  "Sal (incluidas la de mesa y la desnaturalizada) y ...",
    "2504"  :  "Grafito natural",
    "2505"  :  "Arenas naturales de cualquier clase, incluso color...",
    "2506"  :  "Cuarzo (excepto las arenas naturales); cuarcita, i...",
    "2507"  :  "Caolín y demás arcillas caolínicas, incluso calcin...",
    "2508"  :  "Las demás arcillas (excepto las arcillas dilatadas...",
    "2510"  :  "Fosfatos de calcio naturales, fosfatos aluminocálc...",
    "2511"  :  "Sulfato de bario natural (baritina); carbonato de ...",
    "2512"  :  "Harinas silíceas fósiles (por ejemplo: 'Kieselguhr...",
    "2513"  :  "Piedra pómez; esmeril; corindón natural, granate n...",
    "2515"  :  "Mármol, travertinos, 'ecaussines' y demás piedras ...",
    "2516"  :  "Granito, pórfido, basalto, arenisca y demás piedra...",
    "2517"  :  "Cantos, grava, piedras machacadas, de los tipos ge...",
    "2518"  :  "Dolomita, incluso sinterizada o calcinada, incluid...",
    "2519"  :  "Carbonato de magnesio natural (magnesita); magnesi...",
    "2520"  :  "Yeso natural; anhidrita; yeso fraguable (consisten...",
    "2522"  :  "Cal viva, cal apagada y cal hidráulica, excepto el...",
    "2523"  :  "Cementos hidráulicos (comprendidos los cementos si...",
    "2525"  :  "Mica, incluida la exfoliada en laminillas irregula...",
    "2526"  :  "Esteatita natural, incluso desbastada o simplement...",
    "2528"  :  "Boratos naturales y sus concentrados (incluso calc...",
    "2529"  :  "Feldespato; leucita; nefelina y nefelina sienita; ...",
    "2530"  :  "Materias minerales no expresadas ni comprendidas e...",
    "2601"  :  "Minerales de hierro y sus concentrados, incluidas ...",
    "2602"  :  "Minerales de manganeso y sus concentrados, incluid...",
    "2603"  :  "Minerales de cobre y sus concentrados",
    "2605"  :  "Minerales de cobalto y sus concentrados",
    "2607"  :  "Minerales de plomo y sus concentrados",
    "2608"  :  "Minerales de cinc y sus concentrados",
    "2610"  :  "Minerales de cromo y sus concentrados",
    "2613"  :  "Minerales de molibdeno y sus concentrados",
    "2614"  :  "Minerales de titanio y sus concentrados",
    "2615"  :  "Minerales de niobio, tantalio, vanadio o circonio,...",
    "2616"  :  "Minerales de los metales preciosos y sus concentra...",
    "2617"  :  "Los demás minerales y sus concentrados",
    "2619"  :  "Escorias (excepto las granuladas), batiduras y dem...",
    "2620"  :  "Escorias, cenizas y residuos (excepto los de la si...",
    "2621"  :  "Las demás escorias y cenizas, incluidas las ceniza...",
    "2701"  :  "Hullas; briquetas, ovoides y combustibles sólidos ...",
    "2703"  :  "Turba (comprendida la utilizada para cama de anima...",
    "2704"  :  "Coques y semicoques de hulla, lignito o turba, inc...",
    "2707"  :  "Aceites y demás productos de la destilación de los...",
    "2708"  :  "Brea y coque de brea de alquitrán de hulla o de ot...",
    "2709"  :  "Aceites crudos de petróleo o de mineral bituminoso",
    "2710"  :  "Aceites de petróleo o de mineral bituminoso, excep...",
    "2711"  :  "Gas de petróleo y demás hidrocarburos gaseosos",
    "2712"  :  "Vaselina; parafina, cera de petróleo microcristali...",
    "2713"  :  "Coque de petróleo, betún de petróleo y demás resid...",
    "2714"  :  "Betunes y asfaltos naturales; pizarras y arenas bi...",
    "2715"  :  "Mezclas bituminosas a base de asfalto o de betún n...",
    "2716"  :  "Energía eléctrica",
    "2801"  :  "Flúor, cloro, bromo y yodo",
    "2803"  :  "Carbono (negros de humo y otras formas de carbono ...",
    "2804"  :  "Hidrógeno, gases nobles y demás elementos no metál...",
    "2805"  :  "Metales alcalinos o alcalinotérreos; metales de la...",
    "2806"  :  "Cloruro de hidrógeno (ácido clorhídrico); ácido cl...",
    "2807"  :  "Ácido sulfúrico; oleum",
    "2808"  :  "Ácido nítrico; ácidos sulfonítricos",
    "2809"  :  "Pentóxido de difósforo; ácido fosfórico; ácidos po...",
    "2810"  :  "Óxidos de boro; ácidos bóricos",
    "2811"  :  "Los demás ácidos inorgánicos y los demás compuesto...",
    "2814"  :  "Amoníaco anhidro o en disolución acuosa",
    "2815"  :  "Hidróxido de sodio (sosa o soda cáustica); hidróxi...",
    "2816"  :  "Hidróxido y peróxido de magnesio; óxidos, hidróxid...",
    "2817"  :  "Óxido de cinc; peróxido de cinc",
    "2818"  :  "Corindón artificial, aunque no sea de constitución...",
    "2819"  :  "Óxidos e hidróxidos de cromo",
    "2820"  :  "Óxidos de manganeso",
    "2821"  :  "Óxidos e hidróxidos de hierro; tierras colorantes ...",
    "2822"  :  "Óxidos e hidróxidos de cobalto; óxidos de cobalto ...",
    "2823"  :  "Óxidos de titanio",
    "2824"  :  "Óxidos de plomo; minio y minio anaranjado",
    "2825"  :  "Hidrazina e hidroxilamina y sus sales inorgánicas;...",
    "2826"  :  "Fluoruros; fluorosilicatos, fluoroaluminatos y dem...",
    "2827"  :  "Cloruros, oxicloruros e hidroxicloruros; bromuros ...",
    "2828"  :  "Hipocloritos; hipoclorito de calcio comercial; clo...",
    "2829"  :  "Cloratos y percloratos; bromatos y perbromatos; yo...",
    "2830"  :  "Sulfuros; polisulfuros, aunque no sean de constitu...",
    "2832"  :  "Sulfitos; tiosulfatos",
    "2833"  :  "Sulfatos; alumbres; peroxosulfatos (persulfatos)",
    "2834"  :  "Nitritos; nitratos",
    "2835"  :  "Fosfinatos (hipofosfitos), fosfonatos (fosfitos) y...",
    "2836"  :  "Carbonatos; peroxocarbonatos (percarbonatos); carb...",
    "2837"  :  "Cianuros, oxicianuros y cianuros complejos",
    "2839"  :  "Silicatos; silicatos comerciales de los metales al...",
    "2840"  :  "Boratos; peroxoboratos (perboratos)",
    "2841"  :  "Sales de los ácidos oxometálicos o peroxometálicos",
    "2842"  :  "Las demás sales de los ácidos o peroxoácidos inorg...",
    "2843"  :  "Metal precioso en estado coloidal; compuestos inor...",
    "2844"  :  "Elementos químicos radiactivos e isótopos radiacti...",
    "2846"  :  "Compuestos inorgánicos u orgánicos, de metales de ...",
    "2847"  :  "Peróxido de hidrógeno (agua oxigenada), incluso so...",
    "2849"  :  "Carburos, aunque no sean de constitución química d...",
    "2850"  :  "Hidruros, nitruros, aziduros (azidas), siliciuros ...",
    "2853"  :  "Los demás compuestos inorgánicos (incluida el agua...",
    "2901"  :  "Hidrocarburos acíclicos",
    "2902"  :  "Hidrocarburos cíclicos",
    "2903"  :  "Derivados halogenados de los hidrocarburos",
    "2904"  :  "Derivados sulfonados, nitrados o nitrosados de los...",
    "2905"  :  "Alcoholes acíclicos y sus derivados halogenados, s...",
    "2906"  :  "Alcoholes cíclicos y sus derivados halogenados, su...",
    "2907"  :  "Fenoles; fenoles-alcoholes",
    "2908"  :  "Derivados halogenados, sulfonados, nitrados o nitr...",
    "2909"  :  "Éteres, éteres-alcoholes, éteres-fenoles, éteres-a...",
    "2910"  :  "Epóxidos, epoxialcoholes, epoxifenoles y epoxiéter...",
    "2911"  :  "Acetales y semiacetales, incluso con otras funcion...",
    "2912"  :  "Aldehídos, incluso con otras funciones oxigenadas;...",
    "2914"  :  "Cetonas y quinonas, incluso con otras funciones ox...",
    "2915"  :  "Ácidos monocarboxílicos acíclicos saturados y sus ...",
    "2916"  :  "Ácidos monocarboxílicos acíclicos no saturados y á...",
    "2917"  :  "Ácidos policarboxílicos, sus anhídridos, halogenur...",
    "2918"  :  "Ácidos carboxílicos con funciones oxigenadas suple...",
    "2919"  :  "Ésteres fosfóricos y sus sales, incluidos los lact...",
    "2920"  :  "Ésteres de los demás ácidos inorgánicos de los no ...",
    "2921"  :  "Compuestos con función amina",
    "2922"  :  "Compuestos aminados con funciones oxigenadas",
    "2923"  :  "Sales e hidróxidos de amonio cuaternario; lecitina...",
    "2924"  :  "Compuestos con función carboxiamida; compuestos co...",
    "2925"  :  "Compuestos con función carboxiimida (incluida la s...",
    "2926"  :  "Compuestos con función nitrilo",
    "2927"  :  "Compuestos diazoicos, azoicos o azoxi",
    "2928"  :  "Derivados orgánicos de la hidrazina o de la hidrox...",
    "2929"  :  "Compuestos con otras funciones nitrogenadas",
    "2930"  :  "Tiocompuestos orgánicos",
    "2931"  :  "Los demás compuestos órgano-inorgánicos",
    "2932"  :  "Compuestos heterocíclicos con heteroátomo(s) de ox...",
    "2933"  :  "Compuestos heterocíclicos con heteroátomo(s) de ni...",
    "2934"  :  "Ácidos nucleicos y sus sales, aunque no sean de co...",
    "2935"  :  "Sulfonamidas",
    "2936"  :  "Provitaminas y vitaminas, naturales o reproducidas...",
    "2937"  :  "Hormonas, prostaglandinas, tromboxanos y leucotrie...",
    "2938"  :  "Heterósidos, naturales o reproducidos por síntesis...",
    "2939"  :  "Alcaloides vegetales, naturales o reproducidos por...",
    "2940"  :  "Azúcares químicamente puros, excepto la sacarosa, ...",
    "2941"  :  "Antibióticos",
    "2942"  :  "Los demás compuestos orgánicos",
    "3001"  :  "Glándulas y demás órganos para usos opoterápicos, ...",
    "3002"  :  "Sangre humana; sangre animal preparada para usos t...",
    "3003"  :  "Medicamentos (excepto los productos de las partida...",
    "3004"  :  "Medicamentos (excepto los productos de las partida...",
    "3005"  :  "Guatas, gasas, vendas y artículos análogos (por ej...",
    "3006"  :  "Preparaciones y artículos farmacéuticos a que se r...",
    "3101"  :  "Abonos de origen animal o vegetal, incluso mezclad...",
    "3102"  :  "Abonos minerales o químicos nitrogenados",
    "3103"  :  "Abonos minerales o químicos fosfatados",
    "3104"  :  "Abonos minerales o químicos potásicos",
    "3105"  :  "Abonos minerales o químicos, con dos o tres de los...",
    "3201"  :  "Extractos curtientes de origen vegetal; taninos y ...",
    "3202"  :  "Productos curtientes orgánicos sintéticos; product...",
    "3203"  :  "Materias colorantes de origen vegetal o animal (in...",
    "3204"  :  "Materias colorantes orgánicas sintéticas, aunque s...",
    "3205"  :  "Lacas colorantes; preparaciones a que se refiere l...",
    "3206"  :  "Las demás materias colorantes; preparaciones a que...",
    "3207"  :  "Pigmentos, opacificantes y colores preparados, com...",
    "3208"  :  "Pinturas y barnices a base de polímeros sintéticos...",
    "3209"  :  "Pinturas y barnices a base de polímeros sintéticos...",
    "3210"  :  "Las demás pinturas y barnices; pigmentos al agua p...",
    "3211"  :  "Secativos preparados",
    "3212"  :  "Pigmentos (incluidos el polvo y escamillas metálic...",
    "3213"  :  "Colores para la pintura artística, la enseñanza, l...",
    "3214"  :  "Masilla, cementos de resina y demás mástiques; pla...",
    "3215"  :  "Tintas de imprimir, tintas de escribir o de dibuja...",
    "3301"  :  "Aceites esenciales (desterpenados o no), incluidos...",
    "3302"  :  "Mezclas de sustancias odoríferas y mezclas (inclui...",
    "3303"  :  "Perfumes y aguas de tocador",
    "3304"  :  "Preparaciones de belleza, maquillaje y para el cui...",
    "3305"  :  "Preparaciones capilares",
    "3306"  :  "Preparaciones para higiene bucal o dental, incluid...",
    "3307"  :  "Preparaciones para afeitar o para antes o después ...",
    "3401"  :  "Jabón; productos y preparaciones orgánicos tensoac...",
    "3402"  :  "Agentes de superficie orgánicos (excepto el jabón)...",
    "3403"  :  "Preparaciones lubricantes (incluidos los aceites d...",
    "3404"  :  "Ceras artificiales y ceras preparadas",
    "3405"  :  "Betunes y cremas para el calzado, encáusticos, abr...",
    "3406"  :  "Velas, cirios y artículos similares",
    "3407"  :  "Pastas para modelar, incluidas las presentadas par...",
    "3501"  :  "Caseína, caseinatos y demás derivados de la caseín...",
    "3502"  :  "Albúminas (incluidos los concentrados de varias pr...",
    "3503"  :  "Gelatinas (aunque se presenten en hojas cuadradas ...",
    "3504"  :  "Peptonas y sus derivados; las demás materias prote...",
    "3505"  :  "Dextrina y demás almidones y féculas modificados (...",
    "3506"  :  "Colas y demás adhesivos preparados, no expresados ...",
    "3507"  :  "Enzimas; preparaciones enzimáticas no expresadas n...",
    "3602"  :  "Explosivos preparados, excepto la pólvora",
    "3603"  :  "Mechas de seguridad; cordones detonantes; cebos y ...",
    "3605"  :  "Fósforos (cerillas), excepto los artículos de piro...",
    "3606"  :  "Ferrocerio y demás aleaciones pirofóricas en cualq...",
    "3701"  :  "Placas y películas planas, fotográficas, sensibili...",
    "3702"  :  "Películas fotográficas en rollos, sensibilizadas, ...",
    "3703"  :  "Papel, cartón y textiles, fotográficos, sensibiliz...",
    "3705"  :  "Placas y películas, fotográficas, impresionadas y ...",
    "3707"  :  "Preparaciones químicas para uso fotográfico, excep...",
    "3801"  :  "Grafito artificial; grafito coloidal o semicoloida...",
    "3802"  :  "Carbón activado; materias minerales naturales acti...",
    "3804"  :  "Lejías residuales de la fabricación de pastas de c...",
    "3805"  :  "Esencias de trementina, de madera de pino o de pas...",
    "3806"  :  "Colofonias y ácidos resínicos, y sus derivados; es...",
    "3808"  :  "Insecticidas, raticidas y demás antirroedores, fun...",
    "3809"  :  "Aprestos y productos de acabado, aceleradores de t...",
    "3810"  :  "Preparaciones para el decapado de metal; flujos y ...",
    "3811"  :  "Preparaciones antidetonantes, inhibidores de oxida...",
    "3812"  :  "Aceleradores de vulcanización preparados; plastifi...",
    "3813"  :  "Preparaciones y cargas para aparatos extintores; g...",
    "3814"  :  "Disolventes y diluyentes orgánicos compuestos, no ...",
    "3815"  :  "Iniciadores y aceleradores de reacción y preparaci...",
    "3816"  :  "Cementos, morteros, hormigones y preparaciones sim...",
    "3818"  :  "Elementos químicos dopados para uso en electrónica...",
    "3819"  :  "Líquidos para frenos hidráulicos y demás líquidos ...",
    "3820"  :  "Preparaciones anticongelantes y líquidos preparado...",
    "3821"  :  "Medios de cultivo preparados para el desarrollo o ...",
    "3822"  :  "Reactivos de diagnóstico o de laboratorio sobre cu...",
    "3823"  :  "Ácidos grasos monocarboxílicos industriales; aceit...",
    "3824"  :  "Preparaciones aglutinantes para moldes o núcleos d...",
    "3825"  :  "Productos residuales de la industria química o de ...",
    "3827"  :  "Mezclas que contengan derivados halogenados de met...",
    "3901"  :  "Polímeros de etileno en formas primarias",
    "3902"  :  "Polímeros de propileno o de otras olefinas, en for...",
    "3903"  :  "Polímeros de estireno en formas primarias",
    "3904"  :  "Polímeros de cloruro de vinilo o de otras olefinas...",
    "3905"  :  "Polímeros de acetato de vinilo o de otros ésteres ...",
    "3906"  :  "Polímeros acrílicos en formas primarias",
    "3907"  :  "Poliacetales, los demás poliéteres y resinas epoxi...",
    "3908"  :  "Poliamidas en formas primarias",
    "3909"  :  "Resinas amínicas, resinas fenólicas y poliuretanos...",
    "3910"  :  "Siliconas en formas primarias",
    "3911"  :  "Resinas de petróleo, resinas de cumarona-indeno, p...",
    "3912"  :  "Celulosa y sus derivados químicos, no expresados n...",
    "3913"  :  "Polímeros naturales (por ejemplo, ácido algínico) ...",
    "3914"  :  "Intercambiadores de iones a base de polímeros de l...",
    "3915"  :  "Desechos, desperdicios y recortes, de plástico",
    "3916"  :  "Monofilamentos cuya mayor dimensión del corte tran...",
    "3917"  :  "Tubos y accesorios de tubería (por ejemplo: juntas...",
    "3918"  :  "Revestimientos de plástico para suelos, incluso au...",
    "3919"  :  "Placas, láminas, hojas, cintas, tiras y demás form...",
    "3920"  :  "Las demás placas, láminas, hojas y tiras, de plást...",
    "3921"  :  "Las demás placas, láminas, hojas y tiras, de plást...",
    "3922"  :  "Bañeras, duchas, fregaderos (tarjas), lavabos, bid...",
    "3923"  :  "Artículos para el transporte o envasado, de plásti...",
    "3924"  :  "Vajilla y demás artículos de uso doméstico y artíc...",
    "3925"  :  "Artículos para la construcción, de plástico, no ex...",
    "3926"  :  "Las demás manufacturas de plástico y manufacturas ...",
    "4001"  :  "Caucho natural, balata, gutapercha, guayule, chicl...",
    "4002"  :  "Caucho sintético y caucho facticio derivado de los...",
    "4004"  :  "Desechos, desperdicios y recortes, de caucho sin e...",
    "4005"  :  "Caucho mezclado sin vulcanizar, en formas primaria...",
    "4006"  :  "Las demás formas (por ejemplo: varillas, tubos, pe...",
    "4007"  :  "Hilos y cuerdas, de caucho vulcanizado",
    "4008"  :  "Placas, hojas, tiras, varillas y perfiles, de cauc...",
    "4009"  :  "Tubos de caucho vulcanizado sin endurecer, incluso...",
    "4010"  :  "Correas transportadoras o de transmisión, de cauch...",
    "4011"  :  "Neumáticos nuevos de caucho",
    "4012"  :  "Neumáticos recauchutados o usados, de caucho; band...",
    "4013"  :  "Cámaras de caucho para neumáticos",
    "4014"  :  "Artículos de higiene o de farmacia (comprendidas l...",
    "4015"  :  "Prendas de vestir, guantes, mitones y manoplas y d...",
    "4016"  :  "Las demás manufacturas de caucho vulcanizado sin e...",
    "4017"  :  "Caucho endurecido (por ejemplo, ebonita) en cualqu...",
    "4101"  :  "Cueros y pieles en bruto, de bovino (incluido el b...",
    "4104"  :  "Cueros y pieles curtidos o 'crust', de bovino (inc...",
    "4105"  :  "Pieles curtidas o 'crust', de ovino, depiladas, in...",
    "4106"  :  "Cueros y pieles depilados de los demás animales y ...",
    "4107"  :  "Cueros preparados después del curtido o del secado...",
    "4113"  :  "Cueros preparados después del curtido o secado y c...",
    "4114"  :  "Cueros y pieles agamuzados (incluido el agamuzado ...",
    "4115"  :  "Cuero regenerado a base de cuero o fibras de cuero...",
    "4201"  :  "Artículos de talabartería o de guarnicionería para...",
    "4202"  :  "Baúles, maletas (valijas), maletines, incluidos lo...",
    "4203"  :  "Prendas y complementos (accesorios), de vestir, de...",
    "4205"  :  "Las demás manufacturas de cuero natural o cuero re...",
    "4206"  :  "Manufacturas de tripa, vejigas o tendones",
    "4302"  :  "Peletería curtida o adobada (incluidas las cabezas...",
    "4303"  :  "Prendas y complementos (accesorios), de vestir, y ...",
    "4304"  :  "Peletería facticia o artificial y artículos de pel...",
    "4401"  :  "Leña; madera en plaquitas o partículas; aserrín, d...",
    "4402"  :  "Carbón vegetal (comprendido el de cáscaras o de hu...",
    "4403"  :  "Madera en bruto, incluso descortezada, desalburada...",
    "4404"  :  "Flejes de madera; rodrigones hendidos; estacas y e...",
    "4405"  :  "Lana de madera; harina de madera",
    "4407"  :  "Madera aserrada o desbastada longitudinalmente, co...",
    "4408"  :  "Hojas para chapado (incluidas las obtenidas por co...",
    "4409"  :  "Madera (incluidas las tablillas y frisos para parq...",
    "4410"  :  "Tableros de partículas, tableros llamados 'oriente...",
    "4411"  :  "Tableros de fibra de madera u otras materias leños...",
    "4412"  :  "Madera contrachapada, madera chapada y madera estr...",
    "4413"  :  "Madera densificada en bloques, tablas, tiras o per...",
    "4414"  :  "Marcos de madera para cuadros, fotografías, espejo...",
    "4415"  :  "Cajones, cajas, jaulas, tambores y envases similar...",
    "4416"  :  "Barriles, cubas, tinas y demás manufacturas de ton...",
    "4417"  :  "Herramientas, monturas y mangos de herramientas, m...",
    "4418"  :  "Obras y piezas de carpintería para construcciones,...",
    "4419"  :  "Artículos de mesa o de cocina, de madera",
    "4420"  :  "Marquetería y taracea; cofrecillos y estuches para...",
    "4421"  :  "Las demás manufacturas de madera",
    "4501"  :  "Corcho natural en bruto o simplemente preparado; d...",
    "4503"  :  "Manufacturas de corcho natural",
    "4504"  :  "Corcho aglomerado (incluso con aglutinante) y manu...",
    "4601"  :  "Trenzas y artículos similares, de materia trenzabl...",
    "4602"  :  "Artículos de cestería obtenidos directamente en su...",
    "4707"  :  "Papel o cartón para reciclar (desperdicios y desec...",
    "4801"  :  "Papel prensa en bobinas (rollos) o en hojas",
    "4802"  :  "Papel y cartón, sin estucar ni recubrir, de los ti...",
    "4803"  :  "Papel del tipo utilizado para papel higiénico, toa...",
    "4804"  :  "Papel y cartón Kraft, sin estucar ni recubrir, en ...",
    "4805"  :  "Los demás papeles y cartones, sin estucar ni recub...",
    "4806"  :  "Papel y cartón sulfurizados, papel resistente a la...",
    "4807"  :  "Papel y cartón obtenidos por pegado de hojas plana...",
    "4808"  :  "Papel y cartón corrugados (incluso revestidos por ...",
    "4809"  :  "Papel carbón (carbónico), papel autocopia y demás ...",
    "4810"  :  "Papel y cartón estucados por una o las dos caras c...",
    "4811"  :  "Papel, cartón, guata de celulosa y napa de fibras ...",
    "4812"  :  "Bloques y placas, filtrantes, de pasta de papel",
    "4813"  :  "Papel de fumar, incluso cortado al tamaño adecuado...",
    "4814"  :  "Papel para decorar y revestimientos similares de p...",
    "4816"  :  "Papel carbón (carbónico), papel autocopia y demás ...",
    "4817"  :  "Sobres, sobres carta, tarjetas postales sin ilustr...",
    "4818"  :  "Papel del tipo utilizado para papel higiénico y pa...",
    "4819"  :  "Cajas, sacos (bolsas), bolsitas, cucuruchos y demá...",
    "4820"  :  "Libros registro, libros de contabilidad, talonario...",
    "4821"  :  "Etiquetas de todas clases, de papel o cartón, incl...",
    "4822"  :  "Carretes, bobinas, canillas y soportes similares, ...",
    "4823"  :  "Los demás papeles, cartones, guata de celulosa y n...",
    "4901"  :  "Libros, folletos e impresos similares, incluso en ...",
    "4902"  :  "Diarios y publicaciones periódicas, impresos, incl...",
    "4903"  :  "Álbumes o libros de estampas y cuadernos para dibu...",
    "4904"  :  "Música manuscrita o impresa, incluso con ilustraci...",
    "4905"  :  "Manufacturas cartográficas de todas clases, inclui...",
    "4906"  :  "Planos y dibujos originales hechos a mano, de arqu...",
    "4908"  :  "Calcomanías de cualquier clase",
    "4909"  :  "Tarjetas postales impresas o ilustradas; tarjetas ...",
    "4910"  :  "Calendarios de cualquier clase impresos, incluidos...",
    "4911"  :  "Los demás impresos, incluidas las estampas, grabad...",
    "5004"  :  "Hilados de seda (excepto los hilados de desperdici...",
    "5006"  :  "Hilados de seda o de desperdicios de seda, acondic...",
    "5106"  :  "Hilados de lana cardada sin acondicionar para la v...",
    "5107"  :  "Hilados de lana peinada sin acondicionar para la v...",
    "5111"  :  "Tejidos de lana cardada o pelo fino cardado",
    "5112"  :  "Tejidos de lana peinada o pelo fino peinado",
    "5201"  :  "Algodón sin cardar ni peinar",
    "5202"  :  "Desperdicios de algodón (incluidos los desperdicio...",
    "5203"  :  "Algodón cardado o peinado",
    "5204"  :  "Hilo de coser de algodón, incluso acondicionado pa...",
    "5205"  :  "Hilados de algodón (excepto el hilo de coser) con ...",
    "5206"  :  "Hilados de algodón (excepto el hilo de coser) con ...",
    "5207"  :  "Hilados de algodón (excepto el hilo de coser) acon...",
    "5208"  :  "Tejidos de algodón con un contenido de algodón sup...",
    "5209"  :  "Tejidos de algodón con un contenido de algodón sup...",
    "5210"  :  "Tejidos de algodón con un contenido de algodón inf...",
    "5211"  :  "Tejidos de algodón con un contenido de algodón inf...",
    "5212"  :  "Los demás tejidos de algodón",
    "5301"  :  "Lino en bruto o trabajado, pero sin hilar; estopas...",
    "5305"  :  "Coco, abacá (cáñamo de Manila (Musa textilis Nee))...",
    "5306"  :  "Hilados de lino",
    "5308"  :  "Hilados de las demás fibras textiles vegetales; hi...",
    "5309"  :  "Tejidos de lino",
    "5310"  :  "Tejidos de yute o demás fibras textiles del líber ...",
    "5401"  :  "Hilo de coser de filamentos sintéticos o artificia...",
    "5402"  :  "Hilados de filamentos sintéticos (excepto el hilo ...",
    "5403"  :  "Hilados de filamentos artificiales (excepto el hil...",
    "5404"  :  "Monofilamentos sintéticos de título superior o igu...",
    "5406"  :  "Hilados de filamentos sintéticos o artificiales (e...",
    "5407"  :  "Tejidos de hilados de filamentos sintéticos, inclu...",
    "5408"  :  "Tejidos de hilados de filamentos artificiales, inc...",
    "5501"  :  "Cables de filamentos sintéticos",
    "5503"  :  "Fibras sintéticas discontinuas, sin cardar, peinar...",
    "5504"  :  "Fibras artificiales discontinuas, sin cardar, pein...",
    "5505"  :  "Desperdicios de fibras sintéticas o artificiales (...",
    "5506"  :  "Fibras sintéticas discontinuas, cardadas, peinadas...",
    "5508"  :  "Hilo de coser de fibras sintéticas o artificiales,...",
    "5509"  :  "Hilados de fibras sintéticas discontinuas (excepto...",
    "5510"  :  "Hilados de fibras artificiales discontinuas (excep...",
    "5512"  :  "Tejidos de fibras sintéticas discontinuas con un c...",
    "5513"  :  "Tejidos de fibras sintéticas discontinuas con un c...",
    "5514"  :  "Tejidos de fibras sintéticas discontinuas con un c...",
    "5515"  :  "Los demás tejidos de fibras sintéticas discontinua...",
    "5516"  :  "Tejidos de fibras artificiales discontinuas",
    "5601"  :  "Guata de materia textil y artículos de esta guata;...",
    "5602"  :  "Fieltro, incluso impregnado, recubierto, revestido...",
    "5603"  :  "Tela sin tejer, incluso impregnada, recubierta, re...",
    "5604"  :  "Hilos y cuerdas de caucho revestidos de textiles; ...",
    "5605"  :  "Hilados metálicos e hilados metalizados, incluso e...",
    "5606"  :  "Hilados entorchados, tiras y formas similares de l...",
    "5607"  :  "Cordeles, cuerdas y cordajes, estén o no trenzados...",
    "5608"  :  "Redes de mallas anudadas, en paño o en pieza, fabr...",
    "5609"  :  "Artículos de hilados, tiras o formas similares de ...",
    "5701"  :  "Alfombras de nudo de materia textil, incluso confe...",
    "5702"  :  "Alfombras y demás revestimientos para el suelo, de...",
    "5703"  :  "Alfombras y demás revestimientos para el suelo, de...",
    "5704"  :  "Alfombras y demás revestimientos para el suelo, de...",
    "5705"  :  "Las demás alfombras y revestimientos para el suelo...",
    "5801"  :  "Terciopelo y felpa, excepto los de punto, y tejido...",
    "5802"  :  "Tejidos con bucles del tipo toalla, excepto los pr...",
    "5803"  :  "Tejidos de gasa de vuelta, excepto los productos d...",
    "5804"  :  "Tul, tul-bobinot y tejidos de mallas anudadas; enc...",
    "5805"  :  "Tapicería tejida a mano (gobelinos, Flandes, Aubus...",
    "5806"  :  "Cintas, excepto los artículos de la partida 58.07;...",
    "5807"  :  "Etiquetas, escudos y artículos similares, de mater...",
    "5808"  :  "Trenzas en pieza; artículos de pasamanería y artíc...",
    "5809"  :  "Tejidos de hilos de metal y tejidos de hilados met...",
    "5810"  :  "Bordados en pieza, en tiras o en aplicaciones",
    "5811"  :  "Productos textiles acolchados en pieza, constituid...",
    "5901"  :  "Telas recubiertas de cola o materias amiláceas, de...",
    "5902"  :  "Napas tramadas para neumáticos fabricadas con hila...",
    "5903"  :  "Telas impregnadas, recubiertas, revestidas o estra...",
    "5904"  :  "Linóleo, incluso cortado; revestimientos para el s...",
    "5906"  :  "Telas cauchutadas, excepto las de la partida 59.02",
    "5907"  :  "Las demás telas impregnadas, recubiertas o revesti...",
    "5908"  :  "Mechas de materia textil tejida, trenzada o de pun...",
    "5909"  :  "Mangueras para bombas y tubos similares, de materi...",
    "5910"  :  "Correas transportadoras o de transmisión, de mater...",
    "5911"  :  "Productos y artículos textiles para usos técnicos ...",
    "6001"  :  "Terciopelo, felpa (incluidos los tejidos de punto ...",
    "6002"  :  "Tejidos de punto de anchura inferior o igual a 30 ...",
    "6003"  :  "Tejidos de punto de anchura inferior o igual a 30 ...",
    "6004"  :  "Tejidos de punto de anchura superior a 30 cm, con ...",
    "6005"  :  "Tejidos de punto por urdimbre (incluidos los obten...",
    "6006"  :  "Los demás tejidos de punto",
    "6101"  :  "Abrigos, chaquetones, capas, anoraks, cazadoras y ...",
    "6102"  :  "Abrigos, chaquetones, capas, anoraks, cazadoras y ...",
    "6103"  :  "Trajes (ambos o ternos), conjuntos, chaquetas (sac...",
    "6104"  :  "Trajes sastre, conjuntos, chaquetas (sacos), vesti...",
    "6105"  :  "Camisas de punto para hombres o niños",
    "6106"  :  "Camisas, blusas y blusas camiseras, de punto, para...",
    "6107"  :  "Calzoncillos (incluidos los largos y los slips), c...",
    "6108"  :  "Combinaciones, enaguas, bragas (bombachas, calzone...",
    "6109"  :  "'T-shirts' y camisetas, de punto",
    "6110"  :  "Suéteres (jerseys), 'pullovers', cardiganes, chale...",
    "6111"  :  "Prendas y complementos (accesorios), de vestir, de...",
    "6112"  :  "Conjuntos de abrigo para entrenamiento o deporte (...",
    "6113"  :  "Prendas de vestir confeccionadas con tejidos de pu...",
    "6114"  :  "Las demás prendas de vestir, de punto",
    "6115"  :  "Calzas, panty-medias, leotardos, medias, calcetine...",
    "6116"  :  "Guantes, mitones y manoplas, de punto",
    "6117"  :  "Los demás complementos (accesorios) de vestir conf...",
    "6201"  :  "Abrigos, chaquetones, capas, anoraks, cazadoras y ...",
    "6202"  :  "Abrigos, chaquetones, capas, anoraks, cazadoras y ...",
    "6203"  :  "Trajes (ambos o ternos), conjuntos, chaquetas (sac...",
    "6204"  :  "Trajes sastre, conjuntos, chaquetas (sacos), vesti...",
    "6205"  :  "Camisas para hombres o niños",
    "6206"  :  "Camisas, blusas y blusas camiseras, para mujeres o...",
    "6207"  :  "Camisetas, calzoncillos (incluidos los largos y lo...",
    "6208"  :  "Camisetas, combinaciones, enaguas, bragas (bombach...",
    "6209"  :  "Prendas y complementos (accesorios), de vestir, pa...",
    "6210"  :  "Prendas de vestir confeccionadas con productos de ...",
    "6211"  :  "Conjuntos de abrigo para entrenamiento o deporte (...",
    "6212"  :  "Sostenes (corpiños), fajas, corsés, tirantes (tira...",
    "6213"  :  "Pañuelos de bolsillo",
    "6214"  :  "Chales, pañuelos de cuello, bufandas, mantillas, v...",
    "6215"  :  "Corbatas y lazos similares",
    "6216"  :  "Guantes, mitones y manoplas",
    "6217"  :  "Los demás complementos (accesorios) de vestir conf...",
    "6301"  :  "Mantas",
    "6302"  :  "Ropa de cama, mesa, tocador o cocina",
    "6303"  :  "Visillos y cortinas; guardamalletas y rodapiés de ...",
    "6304"  :  "Los demás artículos de tapicería, excepto los de l...",
    "6305"  :  "Sacos (bolsas) y talegas, para envasar",
    "6306"  :  "Toldos de cualquier clase; tiendas (carpas); velas...",
    "6307"  :  "Los demás artículos confeccionados, incluidos los ...",
    "6308"  :  "Juegos constituidos por piezas de tejido e hilados...",
    "6309"  :  "Artículos de prendería",
    "6310"  :  "Trapos; cordeles, cuerdas y cordajes, de materia t...",
    "6401"  :  "Calzado impermeable con suela y parte superior de ...",
    "6402"  :  "Los demás calzados con suela y parte superior de c...",
    "6403"  :  "Calzado con suela de caucho, plástico, cuero natur...",
    "6404"  :  "Calzado con suela de caucho, plástico, cuero natur...",
    "6405"  :  "Los demás calzados",
    "6406"  :  "Partes de calzado (incluidas las partes superiores...",
    "6504"  :  "Sombreros y demás tocados, trenzados o fabricados ...",
    "6505"  :  "Sombreros y demás tocados, de punto o confeccionad...",
    "6506"  :  "Los demás sombreros y tocados, incluso guarnecidos",
    "6507"  :  "Desudadores, forros, fundas, armaduras, viseras y ...",
    "6601"  :  "Paraguas, sombrillas y quitasoles (incluidos los p...",
    "6602"  :  "Bastones, bastones asiento, látigos, fustas y artí...",
    "6603"  :  "Partes, guarniciones y accesorios para los artícul...",
    "6701"  :  "Pieles y demás partes de ave con sus plumas o plum...",
    "6702"  :  "Flores, follaje y frutos, artificiales, y sus part...",
    "6703"  :  "Cabello peinado, afinado, blanqueado o preparado d...",
    "6704"  :  "Pelucas, barbas, cejas, pestañas, mechones y artíc...",
    "6801"  :  "Adoquines, encintados (bordillos) y losas para pav...",
    "6802"  :  "Piedras de talla o de construcción trabajadas (exc...",
    "6803"  :  "Pizarra natural trabajada y manufacturas de pizarr...",
    "6804"  :  "Muelas y artículos similares, sin bastidor, para m...",
    "6805"  :  "Abrasivos naturales o artificiales en polvo o grán...",
    "6806"  :  "Lana de escoria, de roca y lanas minerales similar...",
    "6807"  :  "Manufacturas de asfalto o de productos similares (...",
    "6808"  :  "Paneles, placas, losetas, bloques y artículos simi...",
    "6809"  :  "Manufacturas de yeso fraguable o de preparaciones ...",
    "6810"  :  "Manufacturas de cemento, hormigón o piedra artific...",
    "6811"  :  "Manufacturas de amiantocemento, celulosacemento o ...",
    "6812"  :  "Amianto (asbesto) en fibras trabajado; mezclas a b...",
    "6813"  :  "Guarniciones de fricción (por ejemplo: hojas, roll...",
    "6814"  :  "Mica trabajada y manufacturas de mica, incluida la...",
    "6815"  :  "Manufacturas de piedra o demás materias minerales ...",
    "6901"  :  "Ladrillos, placas, baldosas y demás piezas cerámic...",
    "6902"  :  "Ladrillos, placas, baldosas y piezas cerámicas aná...",
    "6903"  :  "Los demás artículos cerámicos refractarios (por ej...",
    "6904"  :  "Ladrillos de construcción, bovedillas, cubrevigas ...",
    "6905"  :  "Tejas, elementos de chimenea, conductos de humo, o...",
    "6906"  :  "Tubos, canalones y accesorios de tubería, de cerám...",
    "6907"  :  "Placas y baldosas, de cerámica, sin barnizar ni es...",
    "6909"  :  "Aparatos y artículos, de cerámica, para usos quími...",
    "6910"  :  "Fregaderos (piletas de lavar), lavabos, pedestales...",
    "6911"  :  "Vajilla y demás artículos de uso doméstico, higien...",
    "6912"  :  "Vajilla y demás artículos de uso doméstico, higien...",
    "6913"  :  "Estatuillas y demás artículos para adorno, de cerá...",
    "6914"  :  "Las demás manufacturas de cerámica",
    "7001"  :  "Desperdicios y desechos de vidrio; vidrio en masa",
    "7002"  :  "Vidrio en bolas (excepto las microesferas de la pa...",
    "7003"  :  "Vidrio colado o laminado, en placas, hojas o perfi...",
    "7004"  :  "Vidrio estirado o soplado, en hojas, incluso con c...",
    "7005"  :  "Vidrio flotado y vidrio desbastado o pulido por un...",
    "7006"  :  "Vidrio de las partidas 70.03, 70.04 ó 70.05, curva...",
    "7007"  :  "Vidrio de seguridad constituido por vidrio templad...",
    "7008"  :  "Vidrieras aislantes de paredes múltiples",
    "7009"  :  "Espejos de vidrio, enmarcados o no, incluidos los ...",
    "7010"  :  "Bombonas (damajuanas), botellas, frascos, bocales,...",
    "7011"  :  "Ampollas y envolturas tubulares, abiertas, y sus p...",
    "7013"  :  "Artículos de vidrio para servicio de mesa, cocina,...",
    "7014"  :  "Vidrio para señalización y elementos de óptica de ...",
    "7015"  :  "Cristales para relojes y cristales análogos, crist...",
    "7016"  :  "Adoquines, baldosas, ladrillos, placas, tejas y de...",
    "7017"  :  "Artículos de vidrio para laboratorio, higiene o fa...",
    "7018"  :  "Cuentas de vidrio, imitaciones de perlas, de piedr...",
    "7019"  :  "Fibra de vidrio (incluida la lana de vidrio) y man...",
    "7020"  :  "Las demás manufacturas de vidrio",
    "7101"  :  "Perlas naturales o cultivadas, incluso trabajadas ...",
    "7102"  :  "Diamantes, incluso trabajados, sin montar ni engar...",
    "7103"  :  "Piedras preciosas (excepto los diamantes) o semipr...",
    "7104"  :  "Piedras preciosas o semipreciosas, sintéticas o re...",
    "7106"  :  "Plata (incluida la plata dorada y la platinada) en...",
    "7107"  :  "Chapado (plaqué) de plata sobre metal común, en br...",
    "7108"  :  "Oro (incluido el oro platinado) en bruto, semilabr...",
    "7109"  :  "Chapado (plaqué) de oro sobre metal común o sobre ...",
    "7110"  :  "Platino en bruto, semilabrado o en polvo",
    "7112"  :  "Desperdicios y desechos, de metal precioso o de ch...",
    "7113"  :  "Artículos de joyería y sus partes, de metal precio...",
    "7114"  :  "Artículos de orfebrería y sus partes, de metal pre...",
    "7115"  :  "Las demás manufacturas de metal precioso o de chap...",
    "7116"  :  "Manufacturas de perlas naturales o cultivadas, de ...",
    "7117"  :  "Bisutería",
    "7118"  :  "Monedas",
    "7202"  :  "Ferroaleaciones",
    "7204"  :  "Desperdicios y desechos (chatarra), de fundición, ...",
    "7205"  :  "Granallas y polvo, de fundición en bruto, de fundi...",
    "7206"  :  "Hierro y acero sin alear, en lingotes o demás form...",
    "7207"  :  "Productos intermedios de hierro o acero sin alear",
    "7208"  :  "Productos laminados planos de hierro o acero sin a...",
    "7209"  :  "Productos laminados planos de hierro o acero sin a...",
    "7210"  :  "Productos laminados planos de hierro o acero sin a...",
    "7211"  :  "Productos laminados planos de hierro o acero sin a...",
    "7212"  :  "Productos laminados planos de hierro o acero sin a...",
    "7213"  :  "Alambrón de hierro o acero sin alear",
    "7214"  :  "Barras de hierro o acero sin alear, simplemente fo...",
    "7215"  :  "Las demás barras de hierro o acero sin alear",
    "7216"  :  "Perfiles de hierro o acero sin alear",
    "7217"  :  "Alambre de hierro o acero sin alear",
    "7218"  :  "Acero inoxidable en lingotes o demás formas primar...",
    "7219"  :  "Productos laminados planos de acero inoxidable, de...",
    "7220"  :  "Productos laminados planos de acero inoxidable, de...",
    "7222"  :  "Barras y perfiles, de acero inoxidable",
    "7223"  :  "Alambre de acero inoxidable",
    "7224"  :  "Los demás aceros aleados en lingotes o demás forma...",
    "7225"  :  "Productos laminados planos de los demás aceros ale...",
    "7226"  :  "Productos laminados planos de los demás aceros ale...",
    "7227"  :  "Alambrón de los demás aceros aleados",
    "7228"  :  "Barras y perfiles, de los demás aceros aleados; ba...",
    "7229"  :  "Alambre de los demás aceros aleados",
    "7301"  :  "Tablestacas de hierro o acero, incluso perforadas ...",
    "7302"  :  "Elementos para vías férreas, de fundición, hierro ...",
    "7303"  :  "Tubos y perfiles huecos, de fundición",
    "7304"  :  "Tubos y perfiles huecos, sin costura (sin soldadur...",
    "7305"  :  "Los demás tubos (por ejemplo: soldados o remachado...",
    "7306"  :  "Los demás tubos y perfiles huecos (por ejemplo: so...",
    "7307"  :  "Accesorios de tubería (por ejemplo: empalmes (raco...",
    "7308"  :  "Construcciones y sus partes (por ejemplo: puentes ...",
    "7309"  :  "Depósitos, cisternas, cubas y recipientes similare...",
    "7310"  :  "Depósitos, barriles, tambores, bidones, latas o bo...",
    "7311"  :  "Recipientes para gas comprimido o licuado, de fund...",
    "7312"  :  "Cables, trenzas, eslingas y artículos similares, d...",
    "7313"  :  "Alambre de púas, de hierro o acero; alambre (simpl...",
    "7314"  :  "Telas metálicas (incluidas las continuas o sin fin...",
    "7315"  :  "Cadenas y sus partes, de fundición, hierro o acero",
    "7316"  :  "Anclas, rezones y sus partes, de fundición, hierro...",
    "7317"  :  "Puntas, clavos, chinchetas (chinches), grapas apun...",
    "7318"  :  "Tornillos, pernos, tuercas, tirafondos, escarpias ...",
    "7319"  :  "Agujas de coser, de tejer, pasacintas, agujas de g...",
    "7320"  :  "Muelles (resortes), ballestas y sus hojas, de hier...",
    "7321"  :  "Estufas, calderas con hogar, cocinas (incluidas la...",
    "7322"  :  "Radiadores para calefacción central, de calentamie...",
    "7323"  :  "Artículos de uso doméstico y sus partes, de fundic...",
    "7324"  :  "Artículos de higiene o tocador, y sus partes, de f...",
    "7325"  :  "Las demás manufacturas moldeadas de fundición, hie...",
    "7326"  :  "Las demás manufacturas de hierro o acero",
    "7401"  :  "Matas de cobre; cobre de cementación (cobre precip...",
    "7402"  :  "Cobre sin refinar; ánodos de cobre para refinado e...",
    "7403"  :  "Cobre refinado y aleaciones de cobre, en bruto",
    "7404"  :  "Desperdicios y desechos, de cobre",
    "7405"  :  "Aleaciones madre de cobre",
    "7406"  :  "Polvo y escamillas, de cobre",
    "7407"  :  "Barras y perfiles, de cobre",
    "7408"  :  "Alambre de cobre",
    "7409"  :  "Chapas y tiras, de cobre, de espesor superior a 0....",
    "7410"  :  "Hojas y tiras, delgadas, de cobre (incluso impresa...",
    "7411"  :  "Tubos de cobre",
    "7412"  :  "Accesorios de tubería (por ejemplo: empalmes (raco...",
    "7413"  :  "Cables, trenzas y artículos similares, de cobre, s...",
    "7415"  :  "Puntas, clavos, chinchetas (chinches), grapas apun...",
    "7418"  :  "Artículos de uso doméstico, higiene o tocador, y s...",
    "7419"  :  "Las demás manufacturas de cobre",
    "7502"  :  "Níquel en bruto",
    "7503"  :  "Desperdicios y desechos, de níquel",
    "7505"  :  "Barras, perfiles y alambre, de níquel",
    "7506"  :  "Chapas, hojas y tiras, de níquel",
    "7507"  :  "Tubos y accesorios de tubería (por ejemplo: empalm...",
    "7508"  :  "Las demás manufacturas de níquel",
    "7601"  :  "Aluminio en bruto",
    "7602"  :  "Desperdicios y desechos, de aluminio",
    "7603"  :  "Polvo y escamillas, de aluminio",
    "7604"  :  "Barras y perfiles, de aluminio",
    "7605"  :  "Alambre de aluminio",
    "7606"  :  "Chapas y tiras, de aluminio, de espesor superior a...",
    "7607"  :  "Hojas y tiras, delgadas, de aluminio (incluso impr...",
    "7608"  :  "Tubos de aluminio",
    "7609"  :  "Accesorios de tubería (por ejemplo: empalmes (raco...",
    "7610"  :  "Construcciones y sus partes (por ejemplo: puentes ...",
    "7611"  :  "Depósitos, cisternas, cubas y recipientes similare...",
    "7612"  :  "Depósitos, barriles, tambores, bidones, botes, caj...",
    "7613"  :  "Recipientes para gas comprimido o licuado, de alum...",
    "7614"  :  "Cables, trenzas y similares, de aluminio, sin aisl...",
    "7615"  :  "Artículos de uso doméstico, higiene o tocador, y s...",
    "7616"  :  "Las demás manufacturas de aluminio",
    "7801"  :  "Plomo en bruto",
    "7802"  :  "Desperdicios y desechos, de plomo",
    "7804"  :  "Chapas, hojas y tiras, de plomo; polvo y escamilla...",
    "7806"  :  "Las demás manufacturas de plomo",
    "7901"  :  "Cinc en bruto",
    "7902"  :  "Desperdicios y desechos, de cinc",
    "7903"  :  "Polvo y escamillas, de cinc",
    "7904"  :  "Barras, perfiles y alambre, de cinc",
    "7905"  :  "Chapas, hojas y tiras, de cinc",
    "7907"  :  "Las demás manufacturas de cinc",
    "8001"  :  "Estaño en bruto",
    "8002"  :  "Desperdicios y desechos, de estaño",
    "8003"  :  "Barras, perfiles y alambre, de estaño",
    "8007"  :  "Las demás manufacturas de estaño",
    "8101"  :  "Volframio (tungsteno) y sus manufacturas, incluido...",
    "8103"  :  "Tantalio y sus manufacturas, incluidos los desperd...",
    "8104"  :  "Magnesio y sus manufacturas, incluidos los desperd...",
    "8105"  :  "Matas de cobalto y demás productos intermedios de ...",
    "8106"  :  "Bismuto y sus manufacturas, incluidos los desperdi...",
    "8108"  :  "Titanio y sus manufacturas, incluidos los desperdi...",
    "8109"  :  "Circonio y sus manufacturas, incluidos los desperd...",
    "8110"  :  "Antimonio y sus manufacturas, incluidos los desper...",
    "8111"  :  "Manganeso y sus manufacturas, incluidos los desper...",
    "8112"  :  "Berilio, cromo, germanio, vanadio, galio, hafnio (...",
    "8113"  :  "Cermet y sus manufacturas, incluidos los desperdic...",
    "8201"  :  "Layas, palas, azadas, picos, binaderas, horcas de ...",
    "8202"  :  "Sierras de mano; hojas de sierra de cualquier clas...",
    "8203"  :  "Limas, escofinas, alicates (incluso cortantes), te...",
    "8204"  :  "Llaves de ajuste de mano (incluidas las llaves din...",
    "8205"  :  "Herramientas de mano (incluidos los diamantes de v...",
    "8206"  :  "Herramientas de dos o más de las partidas 82.02 a ...",
    "8207"  :  "Útiles intercambiables para herramientas de mano, ...",
    "8208"  :  "Cuchillas y hojas cortantes, para máquinas o apara...",
    "8209"  :  "Plaquitas, varillas, puntas y artículos similares ...",
    "8210"  :  "Aparatos mecánicos accionados a mano, de peso infe...",
    "8211"  :  "Cuchillos con hoja cortante o dentada, incluidas l...",
    "8212"  :  "Navajas y máquinas de afeitar y sus hojas (incluid...",
    "8213"  :  "Tijeras y sus hojas",
    "8214"  :  "Los demás artículos de cuchillería (por ejemplo: m...",
    "8215"  :  "Cucharas, tenedores, cucharones, espumaderas, pala...",
    "8301"  :  "Candados, cerraduras y cerrojos (de llave, combina...",
    "8302"  :  "Guarniciones, herrajes y artículos similares, de m...",
    "8303"  :  "Cajas de caudales, puertas blindadas y compartimie...",
    "8304"  :  "Clasificadores, ficheros, cajas de clasificación, ...",
    "8305"  :  "Mecanismos para encuadernación de hojas intercambi...",
    "8306"  :  "Campanas, campanillas, gongos y artículos similare...",
    "8307"  :  "Tubos flexibles de metal común, incluso con sus ac...",
    "8308"  :  "Cierres, monturas cierre, hebillas, hebillas cierr...",
    "8309"  :  "Tapones y tapas (incluidas las tapas corona, las t...",
    "8310"  :  "Placas indicadoras, placas rótulo, placas de direc...",
    "8311"  :  "Alambres, varillas, tubos, placas, electrodos y ar...",
    "8402"  :  "Calderas de vapor (generadores de vapor), excepto ...",
    "8403"  :  "Calderas para calefacción central, excepto las de ...",
    "8404"  :  "Aparatos auxiliares para las calderas de las parti...",
    "8405"  :  "Generadores de gas pobre (gas de aire) o de gas de...",
    "8406"  :  "Turbinas de vapor",
    "8407"  :  "Motores de émbolo (pistón) alternativo y motores r...",
    "8408"  :  "Motores de émbolo (pistón) de encendido por compre...",
    "8409"  :  "Partes identificables como destinadas, exclusiva o...",
    "8410"  :  "Turbinas hidráulicas, ruedas hidráulicas y sus reg...",
    "8411"  :  "Turborreactores, turbopropulsores y demás turbinas...",
    "8412"  :  "Los demás motores y máquinas motrices",
    "8413"  :  "Bombas para líquidos, incluso con dispositivo medi...",
    "8414"  :  "Bombas de aire o de vacío, compresores de aire u o...",
    "8415"  :  "Máquinas y aparatos para acondicionamiento de aire...",
    "8416"  :  "Quemadores para la alimentación de hogares, de com...",
    "8417"  :  "Hornos industriales o de laboratorio, incluidos lo...",
    "8418"  :  "Refrigeradores, congeladores y demás material, máq...",
    "8419"  :  "Aparatos y dispositivos, aunque se calienten eléct...",
    "8420"  :  "Calandrias y laminadores, excepto para metal o vid...",
    "8421"  :  "Centrifugadoras, incluidas las secadoras centrífug...",
    "8422"  :  "Máquinas para lavar vajilla; máquinas y aparatos p...",
    "8423"  :  "Aparatos e instrumentos de pesar, incluidas las bá...",
    "8424"  :  "Aparatos mecánicos (incluso manuales) para proyect...",
    "8425"  :  "Polipastos; tornos y cabrestantes; gatos",
    "8426"  :  "Grúas y aparatos de elevación sobre cable aéreo; p...",
    "8427"  :  "Carretillas apiladoras; las demás carretillas de m...",
    "8428"  :  "Las demás máquinas y aparatos de elevación, carga,...",
    "8429"  :  "Topadoras frontales ('bulldozers'), topadoras angu...",
    "8430"  :  "Las demás máquinas y aparatos para explanar, nivel...",
    "8431"  :  "Partes identificables como destinadas, exclusiva o...",
    "8432"  :  "Máquinas, aparatos y artefactos agrícolas, hortíco...",
    "8433"  :  "Máquinas, aparatos y artefactos de cosechar o tril...",
    "8434"  :  "Máquinas de ordeñar y máquinas y aparatos para la ...",
    "8436"  :  "Las demás máquinas y aparatos para la agricultura,...",
    "8437"  :  "Máquinas para limpieza, clasificación o cribado de...",
    "8438"  :  "Máquinas y aparatos, no expresados ni comprendidos...",
    "8439"  :  "Máquinas y aparatos para la fabricación de pasta d...",
    "8440"  :  "Máquinas y aparatos para encuadernación, incluidas...",
    "8441"  :  "Las demás máquinas y aparatos para el trabajo de l...",
    "8442"  :  "Máquinas, aparatos y material (excepto las máquina...",
    "8443"  :  "Máquinas y aparatos para imprimir mediante plancha...",
    "8444"  :  "Máquinas para extrudir, estirar, texturar o cortar...",
    "8445"  :  "Máquinas para la preparación de materia textil; má...",
    "8446"  :  "Telares",
    "8447"  :  "Máquinas de tricotar, de coser por cadeneta, de en...",
    "8448"  :  "Máquinas y aparatos auxiliares para las máquinas d...",
    "8450"  :  "Máquinas para lavar ropa, incluso con dispositivo ...",
    "8451"  :  "Máquinas y aparatos (excepto las máquinas de la pa...",
    "8452"  :  "Máquinas de coser, excepto las de coser pliegos de...",
    "8453"  :  "Máquinas y aparatos para la preparación, curtido o...",
    "8454"  :  "Convertidores, cucharas de colada, lingoteras y má...",
    "8455"  :  "Laminadores para metal y sus cilindros",
    "8456"  :  "Máquinas herramienta que trabajen por arranque de ...",
    "8457"  :  "Centros de mecanizado, máquinas de puesto fijo y m...",
    "8458"  :  "Tornos (incluidos los centros de torneado) que tra...",
    "8459"  :  "Máquinas (incluidas las unidades de mecanizado de ...",
    "8460"  :  "Máquinas de desbarbar, afilar, amolar, rectificar,...",
    "8461"  :  "Máquinas de cepillar, limar, mortajar, brochar, ta...",
    "8462"  :  "Máquinas (incluidas las prensas) de forjar o estam...",
    "8463"  :  "Las demás máquinas herramienta para trabajar metal...",
    "8464"  :  "Máquinas herramienta para trabajar piedra, cerámic...",
    "8465"  :  "Máquinas herramienta (incluidas las de clavar, gra...",
    "8466"  :  "Partes y accesorios identificables como destinados...",
    "8467"  :  "Herramientas neumáticas, hidráulicas o con motor i...",
    "8468"  :  "Máquinas y aparatos para soldar, aunque puedan cor...",
    "8470"  :  "Máquinas de calcular y máquinas de bolsillo regist...",
    "8471"  :  "Máquinas automáticas para tratamiento o procesamie...",
    "8472"  :  "Las demás máquinas y aparatos de oficina (por ejem...",
    "8473"  :  "Partes y accesorios (excepto los estuches, fundas ...",
    "8474"  :  "Máquinas y aparatos de clasificar, cribar, separar...",
    "8475"  :  "Máquinas para montar lámparas, tubos o válvulas el...",
    "8476"  :  "Máquinas automáticas para la venta de productos (p...",
    "8477"  :  "Máquinas y aparatos para trabajar caucho o plástic...",
    "8479"  :  "Máquinas y aparatos mecánicos con función propia, ...",
    "8480"  :  "Cajas de fundición; placas de fondo para moldes; m...",
    "8481"  :  "Artículos de grifería y órganos similares para tub...",
    "8482"  :  "Rodamientos de bolas, de rodillos o de agujas",
    "8483"  :  "Árboles de transmisión (incluidos los de levas y l...",
    "8484"  :  "Juntas metaloplásticas; surtidos de juntas o empaq...",
    "8485"  :  "Reactores nucleares, calderas, máquinas, aparatos ...",
    "8486"  :  "Máquinas y aparatos utilizados, exclusiva o princi...",
    "8487"  :  "Partes de máquinas o aparatos, no expresadas ni co...",
    "8501"  :  "Motores y generadores, eléctricos, excepto los gru...",
    "8502"  :  "Grupos electrógenos y convertidores rotativos eléc...",
    "8503"  :  "Partes identificables como destinadas, exclusiva o...",
    "8504"  :  "Transformadores eléctricos, convertidores eléctric...",
    "8505"  :  "Electroimanes; imanes permanentes y artículos dest...",
    "8506"  :  "Pilas y baterías de pilas, eléctricas",
    "8507"  :  "Acumuladores eléctricos, incluidos sus separadores...",
    "8508"  :  "Aspiradoras",
    "8509"  :  "Aparatos electromecánicos con motor eléctrico inco...",
    "8510"  :  "Afeitadoras, máquinas de cortar el pelo o esquilar...",
    "8511"  :  "Aparatos y dispositivos eléctricos de encendido o ...",
    "8512"  :  "Aparatos eléctricos de alumbrado o señalización (e...",
    "8513"  :  "Lámparas eléctricas portátiles concebidas para fun...",
    "8514"  :  "Hornos eléctricos industriales o de laboratorio, i...",
    "8515"  :  "Máquinas y aparatos para soldar (aunque puedan cor...",
    "8516"  :  "Calentadores eléctricos de agua de calentamiento i...",
    "8517"  :  "Teléfonos, incluidos los teléfonos celulares y los...",
    "8518"  :  "Micrófonos y sus soportes; altavoces (altoparlante...",
    "8519"  :  "Aparatos de grabación de sonido; aparatos de repro...",
    "8521"  :  "Aparatos de grabación o reproducción de imagen y s...",
    "8522"  :  "Partes y accesorios identificables como destinados...",
    "8523"  :  "Discos, cintas, dispositivos de almacenamiento per...",
    "8524"  :  "Máquinas, aparatos y material eléctrico, y sus par...",
    "8525"  :  "Aparatos emisores de radiodifusión o televisión, i...",
    "8526"  :  "Aparatos de radar, radionavegación o radiotelemand...",
    "8527"  :  "Aparatos receptores de radiodifusión, incluso comb...",
    "8528"  :  "Monitores y proyectores, que no incorporen aparato...",
    "8529"  :  "Partes identificables como destinadas, exclusiva o...",
    "8530"  :  "Aparatos eléctricos de señalización (excepto los d...",
    "8531"  :  "Aparatos eléctricos de señalización acústica o vis...",
    "8532"  :  "Condensadores eléctricos fijos, variables o ajusta...",
    "8533"  :  "Resistencias eléctricas, (incluidos reóstatos y po...",
    "8534"  :  "Circuitos impresos",
    "8535"  :  "Aparatos para corte, seccionamiento, protección, d...",
    "8536"  :  "Aparatos para corte, seccionamiento, protección, d...",
    "8537"  :  "Cuadros, paneles, consolas, armarios y demás sopor...",
    "8538"  :  "Partes identificables como destinadas, exclusiva o...",
    "8539"  :  "Lámparas y tubos eléctricos de incandescencia o de...",
    "8540"  :  "Lámparas, tubos y válvulas electrónicos, de cátodo...",
    "8541"  :  "Diodos, transistores y dispositivos semiconductore...",
    "8542"  :  "Circuitos electrónicos integrados",
    "8543"  :  "Máquinas y aparatos eléctricos con función propia,...",
    "8544"  :  "Hilos, cables (incluidos los coaxiales) y demás co...",
    "8545"  :  "Electrodos y escobillas de carbón, carbón para lám...",
    "8546"  :  "Aisladores eléctricos de cualquier materia",
    "8547"  :  "Piezas aislantes totalmente de materia aislante o ...",
    "8548"  :  "Desperdicios y desechos de pilas, baterías de pila...",
    "8549"  :  "Desperdicios y desechos, eléctricos y electrónicos...",
    "8603"  :  "Automotores para vías férreas y tranvías autopropu...",
    "8604"  :  "Vehículos para mantenimiento o servicio de vías fé...",
    "8606"  :  "Vagones para transporte de mercancías sobre carril...",
    "8607"  :  "Partes de vehículos para vías férreas o similares",
    "8608"  :  "Material fijo de vías férreas o similares; aparato...",
    "8609"  :  "Contenedores (incluidos los contenedores cisterna ...",
    "8701"  :  "Tractores (excepto las carretillas tractor de la p...",
    "8702"  :  "Vehículos automóviles para el transporte de diez o...",
    "8703"  :  "Automóviles de turismo y demás vehículos automóvil...",
    "8704"  :  "Vehículos automóviles para el transporte de mercan...",
    "8705"  :  "Vehículos automóviles para usos especiales, except...",
    "8706"  :  "Chasis de vehículos automóviles de las partidas 87...",
    "8707"  :  "Carrocerías de vehículos automóviles de las partid...",
    "8708"  :  "Partes y accesorios de vehículos automóviles de la...",
    "8709"  :  "Carretillas automóvil sin dispositivo de elevación...",
    "8710"  :  "Tanques y demás vehículos automóviles blindados de...",
    "8711"  :  "Motocicletas (incluidos los ciclomotores) y velocí...",
    "8712"  :  "Bicicletas y demás velocípedos (incluidos los tric...",
    "8713"  :  "Sillones de ruedas y demás vehículos para personas...",
    "8714"  :  "Partes y accesorios de vehículos de las partidas 8...",
    "8715"  :  "Coches, sillas y vehículos similares para transpor...",
    "8716"  :  "Remolques y semirremolques para cualquier vehículo...",
    "8801"  :  "Globos y dirigibles; alas planeadoras y demás aero...",
    "8804"  :  "Paracaídas, incluidos los dirigibles, planeadores ...",
    "8806"  :  "Aeronaves no tripuladas.",
    "8807"  :  "Partes de los aparatos de las partidas 88.01, 88.0...",
    "8901"  :  "Trasatlánticos, barcos para excursiones, transbord...",
    "8902"  :  "Barcos de pesca; barcos factoría y demás barcos pa...",
    "8903"  :  "Yates y demás barcos y embarcaciones de recreo o d...",
    "8907"  :  "Los demás artefactos flotantes (por ejemplo: balsa...",
    "8908"  :  "Barcos y demás artefactos flotantes para desguace",
    "9001"  :  "Fibras ópticas y haces de fibras ópticas; cables d...",
    "9002"  :  "Lentes, prismas, espejos y demás elementos de ópti...",
    "9003"  :  "Monturas (armazones) de gafas (anteojos) o artícul...",
    "9004"  :  "Gafas (anteojos) correctoras, protectoras u otras,...",
    "9005"  :  "Binoculares (incluidos los prismáticos), catalejos...",
    "9006"  :  "Cámaras fotográficas; aparatos y dispositivos, inc...",
    "9007"  :  "Cámaras y proyectores cinematográficos, incluso co...",
    "9008"  :  "Proyectores de imagen fija; ampliadoras o reductor...",
    "9010"  :  "Aparatos y material para laboratorios fotográficos...",
    "9011"  :  "Microscopios ópticos, incluso para fotomicrografía...",
    "9012"  :  "Microscopios, excepto los ópticos; difractógrafos",
    "9013"  :  "Dispositivos de cristal líquido que no constituyan...",
    "9014"  :  "Brújulas, incluidos los compases de navegación; lo...",
    "9015"  :  "Instrumentos y aparatos de geodesia, topografía, a...",
    "9016"  :  "Balanzas sensibles a un peso inferior o igual a 5 ...",
    "9017"  :  "Instrumentos de dibujo, trazado o cálculo (por eje...",
    "9018"  :  "Instrumentos y aparatos de medicina, cirugía, odon...",
    "9019"  :  "Aparatos de mecanoterapia; aparatos para masajes; ...",
    "9020"  :  "Los demás aparatos respiratorios y máscaras antigá...",
    "9021"  :  "Artículos y aparatos de ortopedia, incluidas las f...",
    "9022"  :  "Aparatos de rayos X y aparatos que utilicen radiac...",
    "9023"  :  "Instrumentos, aparatos y modelos concebidos para d...",
    "9024"  :  "Máquinas y aparatos para ensayos de dureza, tracci...",
    "9025"  :  "Densímetros, areómetros, pesalíquidos e instrument...",
    "9026"  :  "Instrumentos y aparatos para medida o verificación...",
    "9027"  :  "Instrumentos y aparatos para análisis físicos o qu...",
    "9028"  :  "Contadores de gas, líquido o electricidad, incluid...",
    "9029"  :  "Los demás contadores (por ejemplo: cuentarrevoluci...",
    "9030"  :  "Osciloscopios, analizadores de espectro y demás in...",
    "9031"  :  "Instrumentos, aparatos y máquinas para medida o ve...",
    "9032"  :  "Instrumentos y aparatos para regulación o control ...",
    "9033"  :  "Partes y accesorios, no expresados ni comprendidos...",
    "9101"  :  "Relojes de pulsera, bolsillo y similares (incluido...",
    "9102"  :  "Relojes de pulsera, bolsillo y similares (incluido...",
    "9103"  :  "Despertadores y demás relojes de pequeño mecanismo...",
    "9104"  :  "Relojes de tablero de instrumentos y relojes simil...",
    "9105"  :  "Los demás relojes",
    "9106"  :  "Aparatos de control de tiempo y contadores de tiem...",
    "9107"  :  "Interruptores horarios y demás aparatos que permit...",
    "9108"  :  "Pequeños mecanismos de relojería completos y monta...",
    "9109"  :  "Los demás mecanismos de relojería completos y mont...",
    "9111"  :  "Cajas de los relojes de las partidas 91.01 ó 91.02...",
    "9113"  :  "Pulseras para reloj y sus partes",
    "9114"  :  "Las demás partes de aparatos de relojería",
    "9201"  :  "Pianos, incluso automáticos; clavecines y demás in...",
    "9202"  :  "Los demás instrumentos musicales de cuerda (por ej...",
    "9205"  :  "Instrumentos musicales de viento (por ejemplo: órg...",
    "9206"  :  "Instrumentos musicales de percusión (por ejemplo: ...",
    "9207"  :  "Instrumentos musicales en los que el sonido se pro...",
    "9208"  :  "Cajas de música, orquestriones, organillos, pájaro...",
    "9209"  :  "Partes (por ejemplo, mecanismos de cajas de música...",
    "9302"  :  "Revólveres y pistolas, excepto los de las partidas...",
    "9303"  :  "Las demás armas de fuego y artefactos similares qu...",
    "9304"  :  "Las demás armas (por ejemplo: armas largas y pisto...",
    "9305"  :  "Partes y accesorios de los artículos de las partid...",
    "9306"  :  "Bombas, granadas, torpedos, minas, misiles, cartuc...",
    "9307"  :  "Sables, espadas, bayonetas, lanzas y demás armas b...",
    "9401"  :  "Asientos (excepto los de la partida 94.02), inclus...",
    "9402"  :  "Mobiliario para medicina, cirugía, odontología o v...",
    "9403"  :  "Los demás muebles y sus partes",
    "9404"  :  "Somieres; artículos de cama y artículos similares ...",
    "9405"  :  "Aparatos de alumbrado (incluidos los proyectores) ...",
    "9406"  :  "Construcciones prefabricadas",
    "9503"  :  "Triciclos, patinetes, coches de pedal y juguetes s...",
    "9504"  :  "Consolas y máquinas de videojuegos, artículos para...",
    "9505"  :  "Artículos para fiestas, carnaval u otras diversion...",
    "9506"  :  "Artículos y material para cultura física, gimnasia...",
    "9507"  :  "Cañas de pescar, anzuelos y demás artículos para l...",
    "9508"  :  "Tiovivos, columpios, casetas de tiro y demás atrac...",
    "9601"  :  "Marfil, hueso, concha (caparazón) de tortuga, cuer...",
    "9602"  :  "Materias vegetales o minerales para tallar, trabaj...",
    "9603"  :  "Escobas y escobillas, cepillos, brochas y pinceles...",
    "9604"  :  "Tamices, cedazos y cribas, de mano",
    "9605"  :  "Juegos o surtidos de viaje para aseo personal, cos...",
    "9606"  :  "Botones y botones de presión; formas para botones ...",
    "9607"  :  "Cierres de cremallera (cierres relámpago) y sus pa...",
    "9608"  :  "Bolígrafos; rotuladores y marcadores con punta de ...",
    "9609"  :  "Lápices, minas, pasteles, carboncillos, tizas para...",
    "9610"  :  "Pizarras y tableros para escribir o dibujar, inclu...",
    "9611"  :  "Fechadores, sellos, numeradores, timbradores y art...",
    "9612"  :  "Cintas para máquinas de escribir y cintas similare...",
    "9613"  :  "Encendedores y mecheros, incluso mecánicos o eléct...",
    "9614"  :  "Pipas (incluidas las cazoletas), boquillas para ci...",
    "9615"  :  "Peines, peinetas, pasadores y artículos similares;...",
    "9616"  :  "Pulverizadores de tocador, sus monturas y cabezas ...",
    "9617"  :  "Termos y demás recipientes isotérmicos, montados y...",
    "9618"  :  "Maniquíes y artículos similares; autómatas y escen...",
    "9619"  :  "Toallas sanitarias (compresas) y tampones higiénic...",
    "9620"  :  "Monopies, bípodes, trípodes y artículos similares.",
    "9701"  :  "Pinturas y dibujos, hechos totalmente a mano, exce...",
    "9702"  :  "Grabados, estampas y litografías originales",
    "9703"  :  "Obras originales de estatuaria o escultura, de cua...",
    "9705"  :  "Colecciones y especímenes para colecciones de zool...",
    "9801"  :  "Importaciones o exportaciones de muestras y muestr...",
    "9802"  :  "Maquinaria Regla 8ª",
    "9803"  :  "Material de ensamble para la fabricación de automó...",
    "9804"  :  "Equipajes de pasajeros",
    "9806"  :  "Materiales y equipos sujetos a tratamiento especia...",
    "9901"  :  "No Clasificados",
    "9902"  :  "No Clasificados"
    }