Sección = {
    "I" : "Animales vivos y productos del reino animal",
    "II" : "Productos del reino vegetal",
    "III" : "Grasas y aceites animales o vegetales; productos d...",
    "IV" : "Productos de las industrias alimentarias; bebidas,...",
    "V" : "Productos minerales", 
    "VI": "Productos de las industrias químicas o de las indu...",
    "VII": "Plásticos y sus manufacturas; caucho y sus manufac...",
    "VIII" : "Pieles, cueros, peletería y manufacturas de estas ...",
    "IX" : "Madera, carbón vegetal y manufacturas de madera; c...",
    "X" : "Pasta de madera o de las demás materias fibrosas c...",
    "XI" : "Materias textiles y sus manufacturas",
    "XII" : "Calzado, sombreros y demás tocados, paraguas, quit...", 
    "XIII" : "Manufacturas de piedra, yeso fraguable, cemento, a...",
    "XIV" : "Perlas naturales o cultivadas, piedras preciosas o...", 
    "XV" : "Metales comunes y manufacturas de estos metales", 
    "XVI" : "Máquinas y aparatos, material eléctrico y sus part...", 
    "XVII" : "Material de transporte", 
    "XVIII" : " Instrumentos y aparatos de óptica, fotografía o ci...", 
    "XIX" : "Armas, municiones, y sus partes y accesorios", 
    "XX" : "Mercancías y productos diversos", 
    "XXI" : "Objetos de arte o colección y antigüedades",
    "XXII" : "Operaciones especiales"
           }